name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.119.126.98 << 'EOF'
            cd Todo-list
            git pull origin main

            echo "PORT=${PORT}" > backend/.env
            echo "MONGO_URI=${MONGO_URI}" >> backend/.env
            

            sudo docker-compose down
            sudo docker-compose up --build -d
          EOF
        env:
          PORT: ${{ secrets.PORT }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          
